// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://aylkhplvjjqwnggdtzdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5bGtocGx2ampxd25nZ2R0emRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzMxODUsImV4cCI6MjA2NzY0OTE4NX0.fiotGdK3qFdXYQByiBx6YID9FfiP5I6CGjlg2ySdCVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
